const { PAIRS } = require("../globalPairs");
const { secret } = require("./binance.secret");

const binance = {
  name: "binance",
  url: "https://api.binance.com",
  ...secret,
  getOrderBook(pairIndex) {
    return `${this.url}/api/v1/depth?symbol=${this.pairs[pairIndex]}`;
  },
  pairs: {
    //~130 pairs max (url limitation 2000)
    [PAIRS.BTC_USDT]: "BTCUSDT",
    [PAIRS.ETH_BTC]: "ETHBTC",
    [PAIRS.ETH_USDT]: "ETHUSDT",
    [PAIRS.EOS_BTC]: "EOSBTC",
    [PAIRS.EOS_USDT]: "EOSUSDT",
    [PAIRS.EOS_ETH]: "EOSETH",

    [PAIRS.LTC_USDT]: "LTCUSDT",
    [PAIRS.LTC_BTC]: "LTCBTC",
    [PAIRS.LTC_ETH]: "LTCETH",

    [PAIRS.TRX_USDT]: "TRXUSDT",
    [PAIRS.TRX_BTC]: "TRXBTC",
    [PAIRS.TRX_ETH]: "TRXETH",

    [PAIRS.ADA_ETH]: "ADAETH",
    [PAIRS.ADA_USDT]: "ADAUSDT",
    [PAIRS.ADA_BTC]: "ADABTC",

    [PAIRS.XLM_USDT]: "XLMUSDT",
    [PAIRS.XLM_BTC]: "XLMBTC",
    [PAIRS.XLM_ETH]: "XLMETH",

    [PAIRS.DASH_BTC]: "DASHBTC",
    [PAIRS.DASH_ETH]: "DASHETH",

    [PAIRS.NEO_ETH]: "NEOETH",
    [PAIRS.NEO_USDT]: "NEOUSDT",
    [PAIRS.NEO_BTC]: "NEOBTC",

    [PAIRS.ONT_BTC]: "ONTBTC",
    [PAIRS.ONT_ETH]: "ONTETH",
    [PAIRS.ONT_USDT]: "ONTUSDT",

    [PAIRS.BAT_ETH]: "BATETH",
    [PAIRS.BAT_BTC]: "BATBTC",
    [PAIRS.BAT_USDT]: "BATUSDT",

    [PAIRS.VET_BTC]: "VETBTC",
    [PAIRS.VET_ETH]: "VETETH",
    [PAIRS.VET_USDT]: "VETUSDT",

    [PAIRS.REP_BTC]: "REPBTC",
    [PAIRS.REP_ETH]: "REPETH",

    [PAIRS.QTUM_USDT]: "QTUMUSDT",
    [PAIRS.QTUM_BTC]: "QTUMBTC",
    [PAIRS.QTUM_ETH]: "QTUMETH",

    [PAIRS.ICX_ETH]: "ICXETH",
    [PAIRS.ICX_USDT]: "ICXUSDT",
    [PAIRS.ICX_BTC]: "ICXBTC",

    [PAIRS.ZIL_ETH]: "ZILETH",
    [PAIRS.ZIL_BTC]: "ZILBTC",
    [PAIRS.ZIL_ETH]: "ZILETH",

    [PAIRS.WTC_BTC]: "WTCBTC",
    [PAIRS.WTC_ETH]: "WTCETH",

    [PAIRS.IOST_ETH]: "IOSTETH",
    [PAIRS.IOST_BTC]: "IOSTBTC",
    [PAIRS.IOST_USDT]: "IOSTUSDT",

    [PAIRS.AE_BTC]: "AEBTC",
    [PAIRS.AE_ETH]: "AEETH",

    [PAIRS.AION_ETH]: "AIONETH",
    [PAIRS.AION_BTC]: "AIONBTC",

    [PAIRS.WAN_BTC]: "WANBTC",
    [PAIRS.WAN_ETH]: "WANETH",

    [PAIRS.QKC_BTC]: "QKCBTC",
    [PAIRS.QKC_ETH]: "QKCETH",

    [PAIRS.IOTX_BTC]: "IOTXBTC",
    [PAIRS.IOTX_ETH]: "IOTXETH",

    [PAIRS.BNB_USDT]: "BNBUSDT",
    [PAIRS.BNB_BTC]: "BNBBTC",
    [PAIRS.BNB_ETH]: "BNBETH",

    [PAIRS.NANO_BTC]: "NANOBTC",
    [PAIRS.NANO_ETH]: "NANOETH",

    [PAIRS.MTL_BTC]: "MTLBTC",
    [PAIRS.MTL_ETH]: "MTLETH",

    //Private
    [PAIRS.XMR_BTC]: "XMRBTC",
    [PAIRS.XMR_ETH]: "XMRETH",
    [PAIRS.XMR_USDT]: "XMRUSDT",
    [PAIRS.ZEC_BTC]: "ZECBTC",
    [PAIRS.ZEC_ETH]: "ZECETH",

    // [PAIRS.TUSD_USDT]: "TUSDUSDT",

    // [PAIRS.AGI_BTC]: "AGIBTC",

    // [PAIRS.ARDR_ETH]: "ARDRETH",
    // [PAIRS.AST_ETH]: "ASTETH",
    // [PAIRS.BCC_ETH]: "BCCETH",
    // [PAIRS.BCPT_BTC]: "BCPTBTC",
    // [PAIRS.BCPT_ETH]: "BCPTETH",
    // [PAIRS.BLZ_ETH]: "BLZETH",
    // [PAIRS.BTG_BTC]: "BTGBTC",
    // [PAIRS.BTG_ETH]: "BTGETH",
    // [PAIRS.CLOAK_BTC]: "CLOAKBTC",
    // [PAIRS.CMT_ETH]: "CMTETH",
    // [PAIRS.DENT_ETH]: "DENTETH",
    // [PAIRS.ELF_ETH]: "ELFETH",
    // [PAIRS.MOD_BTC]: "MODBTC",
    // [PAIRS.NCASH_ETH]: "NCASHETH",

    // [PAIRS.NPXS_BTC]: "NPXSBTC",

    // [PAIRS.AMB_BTC]: "AMBBTC",
    // [PAIRS.BRD_BTC]: "BRDBTC",
    // [PAIRS.ENG_ETH]: "ENGETH",
    // [PAIRS.ICN_BTC]: "ICNBTC",
    // [PAIRS.KNC_BTC]: "KNCBTC",
    // [PAIRS.MDA_BTC]: "MDABTC",

    // [PAIRS.RCN_ETH]: "RCNETH",
    // [PAIRS.SKY_ETH]: "SKYETH",

    // [PAIRS.IOTA_USDT]: "IOTAUSDT",

    // [PAIRS.ADX_ETH]: "ADXETH",

    // [PAIRS.AGI_ETH]: "AGIETH",
    // [PAIRS.APPC_ETH]: "APPCETH",
    // [PAIRS.ARN_BTC]: "ARNBTC",
    // [PAIRS.ARN_ETH]: "ARNETH",
    // [PAIRS.AST_BTC]: "ASTBTC",

    // [PAIRS.BCD_BTC]: "BCDBTC",
    // [PAIRS.BLZ_BTC]: "BLZBTC",

    // [PAIRS.BQX_BTC]: "BQXBTC",
    // [PAIRS.BQX_ETH]: "BQXETH",
    // [PAIRS.BRD_ETH]: "BRDETH",
    // [PAIRS.BTS_BTC]: "BTSBTC",
    // [PAIRS.CDT_ETH]: "CDTETH",
    // [PAIRS.CHAT_ETH]: "CHATETH",
    // [PAIRS.CMT_BTC]: "CMTBTC",
    // [PAIRS.CND_ETH]: "CNDETH",
    // [PAIRS.CVC_BTC]: "CVCBTC",

    // [PAIRS.DATA_ETH]: "DATAETH",
    // [PAIRS.DGD_ETH]: "DGDETH",
    // [PAIRS.DNT_BTC]: "DNTBTC",
    // [PAIRS.DNT_ETH]: "DNTETH",
    // [PAIRS.DOCK_ETH]: "DOCKETH",
    // [PAIRS.EDO_ETH]: "EDOETH",
    // [PAIRS.ETC_BTC]: "ETCBTC",
    // [PAIRS.EVX_ETH]: "EVXETH",
    // [PAIRS.FUEL_BTC]: "FUELBTC",
    // [PAIRS.FUN_BTC]: "FUNBTC",
    // [PAIRS.GNT_BTC]: "GNTBTC",
    // [PAIRS.GNT_ETH]: "GNTETH",
    // [PAIRS.GO_BTC]: "GOBTC",
    // [PAIRS.GTO_BTC]: "GTOBTC",
    // [PAIRS.GVT_BTC]: "GVTBTC",
    // [PAIRS.GVT_ETH]: "GVTETH",
    // [PAIRS.HC_BTC]: "HCBTC",
    // [PAIRS.ICN_ETH]: "ICNETH",

    // [PAIRS.IOTA_BTC]: "IOTABTC",

    // [PAIRS.KMD_ETH]: "KMDETH",
    // [PAIRS.LOOM_ETH]: "LOOMETH",
    // [PAIRS.LRC_BTC]: "LRCBTC",
    // [PAIRS.LSK_ETH]: "LSKETH",

    // [PAIRS.LUN_ETH]: "LUNETH",
    // [PAIRS.MCO_ETH]: "MCOETH",
    // [PAIRS.MFT_BTC]: "MFTBTC",
    // [PAIRS.NAV_ETH]: "NAVETH",
    // [PAIRS.PIVX_ETH]: "PIVXETH",
    // [PAIRS.POE_ETH]: "POEETH",
    // [PAIRS.POWR_BTC]: "POWRBTC",
    // [PAIRS.POWR_ETH]: "POWRETH",
    // [PAIRS.PPT_BTC]: "PPTBTC",
    // [PAIRS.REQ_ETH]: "REQETH",
    // [PAIRS.BCC_USDT]: "BCCUSDT",
    // [PAIRS.ETC_USDT]: "ETCUSDT",

    // [PAIRS.NULS_USDT]: "NULSUSDT",
    // [PAIRS.PAX_USDT]: "PAXUSDT",

    // [PAIRS.XRP_USDT]: "XRPUSDT",

    // [PAIRS.ADX_BTC]: "ADXBTC",

    // [PAIRS.AMB_ETH]: "AMBETH",
    // [PAIRS.APPC_BTC]: "APPCBTC",
    // [PAIRS.ARDR_BTC]: "ARDRBTC",
    // [PAIRS.ARK_BTC]: "ARKBTC",
    // [PAIRS.ARK_ETH]: "ARKETH",

    // [PAIRS.BCC_BTC]: "BCCBTC",
    // [PAIRS.BCD_ETH]: "BCDETH",
    // [PAIRS.BNT_BTC]: "BNTBTC",
    // [PAIRS.BNT_ETH]: "BNTETH",
    // [PAIRS.BTS_ETH]: "BTSETH",
    // [PAIRS.CDT_BTC]: "CDTBTC",
    // [PAIRS.CHAT_BTC]: "CHATBTC",
    // [PAIRS.CLOAK_ETH]: "CLOAKETH",
    // [PAIRS.CND_BTC]: "CNDBTC",
    // [PAIRS.CVC_ETH]: "CVCETH",
    // [PAIRS.DATA_BTC]: "DATABTC",
    // [PAIRS.DENT_BTC]: "DENTBTC",
    // [PAIRS.DGD_BTC]: "DGDBTC",
    // [PAIRS.DLT_BTC]: "DLTBTC",
    // [PAIRS.DLT_ETH]: "DLTETH",
    // [PAIRS.DOCK_BTC]: "DOCKBTC",
    // [PAIRS.EDO_BTC]: "EDOBTC",
    // [PAIRS.ELF_BTC]: "ELFBTC",
    // [PAIRS.ENG_BTC]: "ENGBTC",
    // [PAIRS.ENJ_BTC]: "ENJBTC",
    // [PAIRS.ENJ_ETH]: "ENJETH",
    // [PAIRS.ETC_ETH]: "ETCETH",
    // [PAIRS.EVX_BTC]: "EVXBTC",
    // [PAIRS.FUEL_ETH]: "FUELETH",
    // [PAIRS.FUN_ETH]: "FUNETH",
    // [PAIRS.GAS_BTC]: "GASBTC",
    // [PAIRS.GRS_BTC]: "GRSBTC",
    // [PAIRS.GRS_ETH]: "GRSETH",
    // [PAIRS.GTO_ETH]: "GTOETH",
    // [PAIRS.GXS_BTC]: "GXSBTC",
    // [PAIRS.GXS_ETH]: "GXSETH",
    // [PAIRS.HC_ETH]: "HCETH",
    // [PAIRS.HOLOCHAIN_BTC]: "HOTBTC", // for Binance
    // [PAIRS.HOLOCHAIN_ETH]: "HOTETH", // for Binance
    // //[PAIRS.HOT_BTC]: "HOTBTC",
    // //[PAIRS.HOT_ETH]: "HOTETH",

    // [PAIRS.INS_BTC]: "INSBTC",
    // [PAIRS.INS_ETH]: "INSETH",

    // [PAIRS.IOTA_ETH]: "IOTAETH",

    // [PAIRS.KEY_BTC]: "KEYBTC",
    // [PAIRS.KEY_ETH]: "KEYETH",
    // [PAIRS.KMD_BTC]: "KMDBTC",
    // [PAIRS.KNC_ETH]: "KNCETH",
    // [PAIRS.LEND_BTC]: "LENDBTC",
    // [PAIRS.LEND_ETH]: "LENDETH",
    // [PAIRS.LINK_BTC]: "LINKBTC",
    // [PAIRS.LINK_ETH]: "LINKETH",
    // [PAIRS.LOOM_BTC]: "LOOMBTC",
    // [PAIRS.LRC_ETH]: "LRCETH",
    // [PAIRS.LSK_BTC]: "LSKBTC",

    // [PAIRS.LUN_BTC]: "LUNBTC",
    // [PAIRS.MANA_BTC]: "MANABTC",
    // [PAIRS.MANA_ETH]: "MANAETH",
    // [PAIRS.MCO_BTC]: "MCOBTC",
    // [PAIRS.MDA_ETH]: "MDAETH",
    // [PAIRS.MFT_ETH]: "MFTETH",
    // [PAIRS.MOD_ETH]: "MODETH",
    // [PAIRS.MTH_BTC]: "MTHBTC",
    // [PAIRS.MTH_ETH]: "MTHETH",

    // [PAIRS.NAS_BTC]: "NASBTC",
    // [PAIRS.NAS_ETH]: "NASETH",
    // [PAIRS.NAV_BTC]: "NAVBTC",
    // [PAIRS.NCASH_BTC]: "NCASHBTC",
    // [PAIRS.NEBL_BTC]: "NEBLBTC",
    // [PAIRS.NEBL_ETH]: "NEBLETH",
    // [PAIRS.NPXS_ETH]: "NPXSETH",
    // [PAIRS.NULS_BTC]: "NULSBTC",
    // [PAIRS.NULS_ETH]: "NULSETH",
    // [PAIRS.NXS_BTC]: "NXSBTC",
    // [PAIRS.NXS_ETH]: "NXSETH",
    // [PAIRS.OAX_BTC]: "OAXBTC",
    // [PAIRS.OAX_ETH]: "OAXETH",
    // [PAIRS.OMG_BTC]: "OMGBTC",
    // [PAIRS.OMG_ETH]: "OMGETH",

    // [PAIRS.OST_BTC]: "OSTBTC",
    // [PAIRS.OST_ETH]: "OSTETH",
    // [PAIRS.PAX_BTC]: "PAXBTC",
    // [PAIRS.PAX_ETH]: "PAXETH",
    // [PAIRS.PHX_BTC]: "PHXBTC",
    // [PAIRS.PHX_ETH]: "PHXETH",
    // [PAIRS.PIVX_BTC]: "PIVXBTC",
    // [PAIRS.POA_BTC]: "POABTC",
    // [PAIRS.POA_ETH]: "POAETH",
    // [PAIRS.POE_BTC]: "POEBTC",
    // [PAIRS.POLY_BTC]: "POLYBTC",
    // [PAIRS.PPT_ETH]: "PPTETH",

    // [PAIRS.QLC_BTC]: "QLCBTC",
    // [PAIRS.QLC_ETH]: "QLCETH",
    // [PAIRS.QSP_BTC]: "QSPBTC",
    // [PAIRS.QSP_ETH]: "QSPETH",

    // [PAIRS.RCN_BTC]: "RCNBTC",
    // [PAIRS.RDN_BTC]: "RDNBTC",
    // [PAIRS.RDN_ETH]: "RDNETH",

    // [PAIRS.REQ_BTC]: "REQBTC",
    // [PAIRS.RLC_BTC]: "RLCBTC",
    // [PAIRS.RLC_ETH]: "RLCETH",
    // [PAIRS.RVN_BTC]: "RVNBTC",
    // [PAIRS.SALT_BTC]: "SALTBTC",
    // [PAIRS.SALT_ETH]: "SALTETH",
    // [PAIRS.SC_BTC]: "SCBTC",
    // [PAIRS.SC_ETH]: "SCETH",
    // [PAIRS.SKY_BTC]: "SKYBTC",
    // [PAIRS.SNGLS_BTC]: "SNGLSBTC",
    // [PAIRS.SNGLS_ETH]: "SNGLSETH",
    // [PAIRS.SNM_BTC]: "SNMBTC",
    // [PAIRS.SNM_ETH]: "SNMETH",
    // [PAIRS.SNT_BTC]: "SNTBTC",
    // [PAIRS.SNT_ETH]: "SNTETH",
    // [PAIRS.STEEM_BTC]: "STEEMBTC",
    // [PAIRS.STEEM_ETH]: "STEEMETH",
    // [PAIRS.STORJ_BTC]: "STORJBTC",
    // [PAIRS.STORJ_ETH]: "STORJETH",
    // [PAIRS.STORM_BTC]: "STORMBTC",
    // [PAIRS.STORM_ETH]: "STORMETH",
    // [PAIRS.STRAT_BTC]: "STRATBTC",
    // [PAIRS.STRAT_ETH]: "STRATETH",

    // [PAIRS.SYS_BTC]: "SYSBTC",
    // [PAIRS.SYS_ETH]: "SYSETH",
    // [PAIRS.THETA_BTC]: "THETABTC",
    // [PAIRS.THETA_ETH]: "THETAETH",
    // [PAIRS.TNB_BTC]: "TNBBTC",
    // [PAIRS.TNB_ETH]: "TNBETH",
    // [PAIRS.TNT_BTC]: "TNTBTC",
    // [PAIRS.TNT_ETH]: "TNTETH",
    // [PAIRS.TRIG_BTC]: "TRIGBTC",
    // [PAIRS.TRIG_ETH]: "TRIGETH",

    // [PAIRS.TUSD_BTC]: "TUSDBTC",
    // [PAIRS.TUSD_ETH]: "TUSDETH",
    // [PAIRS.VIA_BTC]: "VIABTC",
    // [PAIRS.VIA_ETH]: "VIAETH",
    // [PAIRS.VIB_BTC]: "VIBBTC",
    // [PAIRS.VIB_ETH]: "VIBETH",
    // [PAIRS.VIBE_BTC]: "VIBEBTC",
    // [PAIRS.VIBE_ETH]: "VIBEETH",
    // [PAIRS.WABI_BTC]: "WABIBTC",
    // [PAIRS.WABI_ETH]: "WABIETH",

    // [PAIRS.WAVES_BTC]: "WAVESBTC",
    // [PAIRS.WAVES_ETH]: "WAVESETH",
    // [PAIRS.WINGS_BTC]: "WINGSBTC",
    // [PAIRS.WINGS_ETH]: "WINGSETH",
    // [PAIRS.WPR_BTC]: "WPRBTC",
    // [PAIRS.WPR_ETH]: "WPRETH",

    // [PAIRS.XEM_BTC]: "XEMBTC",
    // [PAIRS.XEM_ETH]: "XEMETH",

    // [PAIRS.XRP_BTC]: "XRPBTC",
    // [PAIRS.XRP_ETH]: "XRPETH",
    // [PAIRS.XVG_BTC]: "XVGBTC",
    // [PAIRS.XVG_ETH]: "XVGETH",
    // [PAIRS.XZC_BTC]: "XZCBTC",
    // [PAIRS.XZC_ETH]: "XZCETH",
    // [PAIRS.YOYO_BTC]: "YOYOBTC",
    // [PAIRS.YOYO_ETH]: "YOYOETH",

    // [PAIRS.ZEN_BTC]: "ZENBTC",
    // [PAIRS.ZEN_ETH]: "ZENETH",

    // [PAIRS.ZRX_BTC]: "ZRXBTC",
    // [PAIRS.ZRX_ETH]: "ZRXETH",
  },
  fees: {
    taker: 0.1, //0.075 bnb
  },
  //https://support.binance.com/hc/en-us/articles/115000594711-Trading-Rule
  minOrder: {
    BTC: 0.001,
    ETH: 0.01,
    USDT: 10,
  },
  mappers: {
    orderbook: data => ({
      bids: data.bids,
      asks: data.asks,
    }),
    order: data => ({ price: data[0], volume: data[1] }),
  },
};

module.exports = { binance };
